spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rabitmq_email
    username: postgres
    password: MainUser
    driver-class-name: org.postgresql.Driver

  rabbitmq:
    addresses:
    virtual-host:
    username:
    password:
    ports:
#    ssl:
#      enabled: false


  jpa:
    hibernate:
    ddl-auto: update
    show-sql: true
    properties:
    dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081

logging:
  leve:
    org.springframework.amqp: DEBUG
    com.rabbitmq.client: DEBUG