spring.application.name=emailrabiqt
server.port = 8080

spring.jpa.hibernate.ddl-auto = update
spring.datasource.url =jdbc:postgresql://localhost:5432/rabitmq_email
spring.datasource.username = postgres
spring.datasoruce.password =MainUser
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
