spring.application.name=userrabitmq
server.port = 8081

spring.jpa.hibernate.ddl-auto = update
spring.datasource.url =jdbc:postgresql://localhost:5432/rabitmq_user
spring.datasource.username = postgres
spring.datasoruce.password =MainUser
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

